### ISSUE TITLE
"description() is deprecated; use Display." error message when parsing fails

### ISSUE THREAD

**Issue by JWorthe** [stevedonovan/chrono-english#15]
When I call `parse_date_string("12:", Local::now(), Dialect::Uk)`, I get the following error:
```
DateError {
    details: "description() is deprecated; use Display",
}
```

**Comment by stevedonovan** [comment]
Version 0.1.5 sorts this out, together with remaining warnings. Thanks @JWorthe

**Comment by JWorthe** [comment]
Thanks Steve!
